### ISSUE TITLE
Dependabot issue

### ISSUE THREAD

**Issue by tech-ticks** [SkyTemple/skytemple-example-plugin#4]
Dependabot showed this error after generating a repo based on this template:

<img width="919" alt="Screenshot 2024-01-10 at 20 30 47" src="https://github.com/SkyTemple/skytemple-example-plugin/assets/65084428/be8a3715-bb87-4f36-bc45-786afe3504a7">

It seems like it's caused by [this line](https://github.com/SkyTemple/skytemple-example-plugin/blob/e714c5718da02dcde2b0c46e6cba5e6f6c692fe1/.github/dependabot.yml#L8).

**Comment by theCapypara** [comment]
ah thanks. Makes sense. I removed it.
